
spring:
  ai:
    dashscope:
      api-key: {API-KEY}
    # multi model switch
    chat:
      client:
        enabled: false
        # 注意：观测数据可能存在敏感信息！
        observations:
          # 记录调用输入
          include-input: true
      observations:
          # 记录 LLMs 输出
          include-completion: true
          # 记录 prompt
          include-prompt: true
          include-error-logging: true

      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: 'classpath:schema-memory.sql'

  # config DB
  datasource:
    url: jdbc:sqlite:db/saa.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false

logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.application: debug

# 部署时不配置，使用默认配置
management:
  endpoints:
    web:
      exposure:
        # 开放所有外部端点
        include: "*"
  endpoint:
    health:
      # 应用健康状态检查，携带详细新学年
      show-details: always
  tracing:
    sampling:
      # trace 采样信息，记录每个请求
      probability: 1.0


